Repository astral-sh/ty-vscode, pull requests merged in 2025-08, with the labels that each got.

#106 Simplify settings handling, delegate to `workspace/configuration`
  package.json
  src/common/server.ts
  src/common/settings.ts
  src/extension.ts
Labels: configuration

#113 Fix release workflow for pre-releases
  .github/workflows/release.yaml
Labels: ci

#119 Add `ty.inlayHints.callArgumentNames` config option
  package.json
  src/common/settings.ts
Labels: configuration

#142 chore(ci): address lint findings
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .github/workflows/zizmor.yaml
Labels: internal, ci
